const VIDEOS = {
  LOAD: "VIDEOS_LOAD",
  LOAD_SUCCESS: "VIDEOS_LOAD_SUCCESS",
  LOAD_FAIL: "VIDEOS_LOAD_FAIL",
};

const CHEMICALS = {
  LOAD: "CHEMICALS_LOAD",
  LOAD_SUCCESS: "CHEMICALS_LOAD_SUCCESS",
  LOAD_FAIL: "CHEMICALS_LOAD_FAIL",
};

export { VIDEOS, CHEMICALS };
